name: htwmusik
dependencies:
- libgfortran=3.0.0=1
- mkl=11.3.3=0
- numpy=1.11.0=py27_1
- openssl=1.0.2h=0
- pip=8.1.1=py27_1
- python=2.7.11=0
- readline=6.2=2
- scipy=0.17.1=np111py27_0
- setuptools=20.7.0=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - argh==0.26.2
  - beautifulsoup4==4.4.1
  - colorama==0.3.7
  - cycler==0.10.0
  - cython==0.24
  - docopt==0.6.2
  - gevent==1.1.1
  - greenlet==0.4.9
  - matplotlib==1.5.1
  - numexpr==2.5.2
  - ocropy==0.2
  - pathtools==0.1.2
  - pillow==3.2.0
  - py==1.4.31
  - pyparsing==2.1.4
  - pytest==2.9.1
  - pytest-watch==4.1.0
  - python-dateutil==2.5.3
  - pytz==2016.4
  - pyyaml==3.11
  - six==1.10.0
  - tables==3.2.2
  - tqdm==4.7.0
  - ujson==1.35
  - virtualenv==15.0.1
  - watchdog==0.8.3

